name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["Type: Bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing. Consider re-reading this section prior to submitting and asking yourself whether someone else can reasonably understand what is written without additional context.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...

      2. With this config...

      3. Run '...'

      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **pip environment**:
          - flasc                         1.0
          - numpy                         1.21.5
          - pandas                        1.4.1
    value: |
        - OS:
        - pip environment (can be retrieved with `pip list`):
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      FLASC text output is valuable to help explain your problem. Text output copy/pasted here is ideal since it is searchable, but sometimes a screen shot is more clear. Use your judgement. Please do not post a screenshot of text.

      This form uses GitHub's Markdown syntax (see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
      When including text output from FLASC or lines of code, they should be wrapped with three ticks (the other symbol on the ~ key in US keyboards), like this:

      ````
      ```
      FLASC-v1.0.0
      Compile Info:
      ```
      ````

      To enable syntax highlighting, add the programming language in the first set of ticks:
      ````
      ```python
      for i in range(5):
        MyPythonFunction()
      ```
      ````


  validations:
    required: false