blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/NREL/flasc/discussions/new
    about: Discuss potential issues or ideas here prior to opening a GitHub Issue